spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME:'username'}:${MONGO_PASSWORD:'password'}@${MONGO_URL:'url'}/${MONGO_DATABASE:'db'}?retryWrites=true&w=majority

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:'access-key'}
        secret-key: ${AWS_SECRET_KEY:'secret-key'}
        instance-profile: true
      region:
        static: ap-northeast-2

server:
  port: ${SERVER_PORT:0}

custom:
  server:
    url:
      frontend: https://${FRONT_SERVER_DOMAIN}
      backend: https://${BACKEND_SERVER_DOMAIN}
    domain:
      frontend: ${FRONT_SERVER_DOMAIN}
      backend: ${BACKEND_SERVER_DOMAIN}

  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    bucket-directory-prefix: ${AWS_BUCKET_PREFIX}

  oauth:
    redirect-uri: https://${BACKEND_SERVER_DOMAIN}/user/signup
    client-id: ${OAUTH_CLIENT_ID}
    client-secret: ${OAUTH_CLIENT_SECRET}

  token:
    rsa-key-location: ${RSA_KEY_LOCATION}
    expire-hour: ${TOKEN_EXPIRE_HOUR}
