name: Build and upload native image

on:
  push:
    branches: ["main"]

env:
  ENVS: "envs"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - name: checkout branch
        uses: actions/checkout@v3

      - name: init graalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm-community'
          components: 'native-image'
          set-java-home: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

#      - name: build native image
#        run: |
#          echo 'spring.profiles.active=server' > ./src/main/resources/application.properties
#          ./gradlew nativeCompile
#
#      - name: upload binary
#        uses: actions/upload-artifact@v2
#        with:
#          name: lutergs-backend
#          path: ./build/native/nativeCompile/*

      - name: login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::622621026293:role/github-actions-lutergs-backend
          role-session-name: github-actions
          aws-region: ap-northeast-2



